### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by KortyBoi** [1Lighty/discord-crasher-checker#2]
I don't think this is DM worthy, but:
I'd say 99% of MP3s, WAVs, OGGs, etc audio files are being marked as crashing media. I have even tested this straight out of Audacity, the plugin will mark it as "This will crash you"
![Image Preview](https://kortyboi.com/img/upload/DiscordCanary_BMv4iWkdLd.png)
![Test Two](https://kortyboi.com/img/upload/DiscordCanary_qFNWKUTCGN.png)

**Comment by 1Lighty** [comment]
I don't think audio files are able to crash Discord, this is an oversight on my end not locking the behavior of the media player to just videos.
