### ISSUE TITLE
Doesn't work - checks forever

### ISSUE THREAD

**Issue by GGORG0** [1Lighty/discord-crasher-checker#3]
It checks every GIF that I look on, but it loads forever and doesn't let me watch it. Tried with safe GIFs and crash GIFs.

**Comment by GGORG0** [comment]
Screenshots:
- Random GIF (safe): https://win10.is-terrible.com/UQX7rL.png
- Crash GIF: https://win10.is-terrible.com/0Ue83W.png
Both have been checking for 1 minute until I gave up and disabled the plugin. This isn't how it's supposed to work, right?

**Comment by 1Lighty** [comment]
You should check to see if it's maybe throwing an error silently by doing ctrl shift i, clicking console, and screenshotting any errors
example error:
![error](https://i.imgur.com/QbFdiuK.png)

**Comment by GGORG0** [comment]
I guess this is the error..? https://win10.is-terrible.com/tYdIS9.png

**Comment by 1Lighty** [comment]
Yup that seems to be it, thanks!

**Comment by GGORG0** [comment]
Ohhh ok I reloaded Discord and now it works. I used the Plugin Downloader plugin to install it, so it didn't require a reload.

**Comment by 1Lighty** [comment]
> Ohhh ok I reloaded Discord and now it works. I used the Plugin Downloader plugin to install it, so it didn't require a reload.

It was still a bug, shouldn't occur any more as of 2545f96c59b7a6b7200e0e8faccde6c9a3773aad, but cache may take a bit for it to take into effect.
