### ISSUE TITLE
Doesn't work on ffmpeg generated files with specific config

### ISSUE THREAD

**Issue by snuckdev** [1Lighty/discord-crasher-checker#4]
Hello. I wrote a discord crasher maker in python (https://github.com/snuckdev/discord-crasher-creator) but this checker doesn't work on some videos of it. Some videos it warns, some it doesn't. Hope you try to fix it.

**Comment by 1Lighty** [comment]
This was likely because I had accidentally left the frame checking limit in place, was removed removed here
https://github.com/1Lighty/discord-crasher-checker/commit/ff26e0d03d3af8c8054088bb1a42523b04fafe72#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2L44
