### ISSUE TITLE
Discord bot?

### ISSUE THREAD

**Issue by itsmeboy0** [1Lighty/discord-crasher-checker#5]
This is a great powercord plugin. However, I want to implement this server-wide (doing something like a ban when a crashing gif is detected).

It would be nice if you could create a bot version of this (a self-hosted bot is sufficient). Thanks.

**Comment by 1Lighty** [comment]
I don't think a bot would be fast enough to react to a crash gif as some crash you the instant you press play (or the instant it is shown to you). It could provide a way to automatically get rid of the gifs, but there will still be casualties.

Have you looked into this btw? Was specifically made for bot developers information.
https://www.reddit.com/r/discordapp/comments/mwsqm2/

**Comment by 1Lighty** [comment]
Discord is fixing it, fix is already present on canary and will be on ptb and stable soon, having a bot for this is a waste of time now.

**Comment by itsmeboy0** [comment]
> Discord is fixing it, fix is already present on canary and will be on ptb and stable soon, having a bot for this is a waste of time now.

Tested it, it seems that gifs that cause Discord to hang (not crash) still work: https://gfycat.com/blissfulflatgalapagostortoise
