### ISSUE TITLE
How do you add this? 

### ISSUE THREAD

**Issue by user9205** [1Lighty/discord-crasher-checker#8]

**Comment by 1Lighty** [comment]
As per the readme
> This is a [Powercord](https://powercord.dev/) plugin, you must use `git clone https://github.com/1Lighty/discord-crasher-checker` in the plugins folder.

or as per the powercord support server instructions for installing plugins

![image](https://i.imgur.com/t3Rx7sO.png)

And before you try and ask, no, this cannot be used on betterdiscord, nor is there a version for betterdiscord, this is exclusively for powercord only.
